name: CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    # ...

  test:
    # ...

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build application (if present)
        run: npm run build 

      - name: Run tests
        run: npm test

      - name: Deploy to Render.com
        uses: johnbeynon/render-deploy-action@v0.0.8
        env:
          RENDER_TOKEN: ${{ secrets.RENDER_TOKEN}}
          SERVICE_ID: ${{ secrets.SERVICE_ID }}
